# Generated by Django 4.1.4 on 2022-12-26 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('item_type', models.CharField(max_length=100)),
                ('item_model_number', models.CharField(max_length=100)),
                ('item_country', models.CharField(max_length=100)),
                ('item_buying_date', models.DateField()),
                ('item_cost', models.CharField(max_length=100)),
                ('item_quantity', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selling_date', models.DateField(blank=True, null=True)),
                ('selling_price', models.CharField(max_length=100)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.stock')),
            ],
        ),
    ]
